version: "2"
networks:
  redis:
services:
  api:
    image: appcivico/pegabot
    container_name: pegabot-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "${EXPOSED_PORT}:${PORT}"
    expose: 
      - "${EXPOSED_PORT}"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    networks:
      - redis
  redis:
    image: "redis"
    container_name: pegabot-api-redis
    command: "redis-server /usr/local/etc/redis/redis.conf --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}"
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
     - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped
    networks:
      - redis
