version: "2"
services:
  api:
    image: appcivico/pegabot
    container_name: pegabot-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "${EXPOSED_PORT}:${PORT}"
    expose: 
      - "${EXPOSED_PORT}"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
